# Generated by Django 5.2.3 on 2025-06-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gst", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gst_user",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gst_user",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="gst_user",
            name="company_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="gst_user",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="gst_user",
            name="pincode",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="gst_user",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gst_user",
            name="gstin",
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name="gst_user",
            name="pan",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
