# Generated by Django 5.2.3 on 2025-06-17 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gst", "0002_gst_user_address_gst_user_city_gst_user_company_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_no", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("gstin", models.CharField(blank=True, max_length=15, null=True)),
                ("customer_name", models.CharField(max_length=255)),
                ("customer_address", models.TextField(blank=True, null=True)),
                ("cgst", models.FloatField(default=0.0)),
                ("sgst", models.FloatField(default=0.0)),
                ("igst", models.FloatField(default=0.0)),
                ("total_amount", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("quantity", models.IntegerField()),
                ("rate", models.FloatField()),
                ("amount", models.FloatField()),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="gst.invoice",
                    ),
                ),
            ],
        ),
    ]
