# Generated by Django 5.2.3 on 2025-06-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gst", "0004_purchase_purchaseitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="claimed_as_itc",
            field=models.BooleanField(default=False),
        ),
    ]
