# Generated by Django 5.2.3 on 2025-06-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gst", "0005_invoice_claimed_as_itc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="claimed_as_itc",
        ),
        migrations.AddField(
            model_name="invoice",
            name="itc_status",
            field=models.CharField(
                choices=[
                    ("claimed", "Claimed"),
                    ("pending", "Pending"),
                    ("reversed", "Reversed"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="itc_status",
            field=models.CharField(
                choices=[
                    ("claimed", "Claimed"),
                    ("pending", "Pending"),
                    ("reversed", "Reversed"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
